#!/usr/bin/env bash
# Install IBKR Gateway credentials without exposing them.
#
# Same approach as ops/set_kraken_key.sh: input is read with echo disabled, so
# nothing reaches the screen, shell history, or the process table.
#
# Run it on the GB10, which is where the Gateway container lives:
#
#     ssh -t -i ~/.ssh/gx10_ed25519 spinner@10.0.0.62 \
#         'cd ~/spintrader-src && ops/set_ibkr_creds.sh'
#
# IMPORTANT: use your PAPER account credentials. IBKR issues the paper account
# a separate username from the live one -- find it under
# Account Settings -> Paper Trading Account in Client Portal. Using live
# credentials here would point the whole system at real money.
set -euo pipefail

ENV_FILE="${SPINTRADER_IBKR_ENV:-$HOME/spintrader/.ibkr}"

if [[ ! -t 0 ]]; then
  echo "error: no terminal attached. Re-run with 'ssh -t ...' so the prompt can hide input." >&2
  exit 1
fi

mkdir -p "$(dirname "$ENV_FILE")"

echo "Installing IBKR Gateway credentials into: $ENV_FILE"
echo "(input is hidden; use your PAPER account username)"
echo

read -r -p  "  Trading mode [paper/live, default paper]: " MODE
MODE="${MODE:-paper}"
if [[ "$MODE" != "paper" && "$MODE" != "live" ]]; then
  echo "error: trading mode must be 'paper' or 'live'." >&2
  exit 1
fi

read -r -s -p "  IBKR username: " IB_USER; echo
read -r -s -p "  IBKR password: " IB_PASS; echo
read -r -s -p "  VNC password (for first login / 2FA screen): " VNC_PASS; echo
echo

IB_USER="$(printf '%s' "$IB_USER" | tr -d '[:space:]')"
if [[ -z "$IB_USER" || -z "$IB_PASS" ]]; then
  echo "error: username and password are both required; nothing written." >&2
  exit 1
fi

if [[ "$MODE" == "live" ]]; then
  echo "WARNING: trading mode is 'live'. The Gateway will connect to the real"
  echo "         account. READ_ONLY_API stays 'yes' regardless, so orders are"
  echo "         still refused until you change it deliberately."
  read -r -p "         Type 'live' to confirm: " CONFIRM
  [[ "$CONFIRM" == "live" ]] || { echo "aborted; nothing written."; exit 1; }
fi

umask 077
TMP="$(mktemp "${ENV_FILE}.XXXXXX")"
trap 'rm -f "$TMP"' EXIT

cat > "$TMP" <<EOF
# IBKR Gateway credentials. Generated by ops/set_ibkr_creds.sh -- do not commit.
TWS_USERID=$IB_USER
TWS_PASSWORD=$IB_PASS
TRADING_MODE=$MODE
READ_ONLY_API=yes
VNC_SERVER_PASSWORD=$VNC_PASS
TIME_ZONE=America/Toronto
AUTO_RESTART_TIME=11:59 PM
EOF

mv "$TMP" "$ENV_FILE"
chmod 600 "$ENV_FILE"
trap - EXIT

unset IB_USER IB_PASS VNC_PASS

echo "Written to $ENV_FILE (mode 600), trading mode: $MODE"
echo
echo "Start the Gateway with:"
echo "    docker compose -f ops/ib-gateway-compose.yml --env-file $ENV_FILE up -d"
echo
echo "Then watch it come up:"
echo "    docker logs -f spintrader-ibgw"
